### PR TITLE
Add scheme configuration support

### PR DESCRIPTION
**Pull request by yavorsky**
client:
```javascript
window.brunch['auto-reload'].ssl = true;
```

### CODE REVIEW

**Comment by es128** [comment]
This will probably not work for many/most people's environments, so the documentation is insufficient. We don't want a bunch of issues being opened asking us to help diagnose ssl problems. 

Need to either provide reliable steps for ensuring the ssl option will work on most local systems, and/or provide a clear disclaimer that users are on their own when it comes to setting up certs correctly.

**Comment by paulmillr** [comment]
no. We should automatically detect SSL based on current uri's protocol.

The main question here was to add ACTUAL support of wss to server.

**Comment by es128** [comment]
See my comments in #47

**Comment by paulmillr** [comment]
Thanks, merged manually because of merge conflicts.

**Pull request closed without merging**
