### PR TITLE
Custom file extensions (#66)

### PR DESCRIPTION
**Pull request by rstacruz**
This implements #66.

### CODE REVIEW

**Comment by es128** [comment]
:+1:

The only concern I have is in the config option keys - `match.css` & `match.js` might be a little confusing in that format since they look so much like filenames.

Maybe something like `match.styles` & `match.refresh` could be considered as alternate names.

**Comment by paulmillr** [comment]
+1 — let's rename this to `stylesheets` and `fullRefresh`

**Comment by rstacruz** [comment]
sounds good, why not:

- `match.stylesheets`
- `match.javascripts`

?

I don't understand `fullRefresh` though, the JavaScript matches don't necessarily do a full page load. Instead, `match.javascripts` will do a live JS reload when `liveJS` is on. The things that will trigger a fullrefresh are those that are not `stylesheets` nor `javascripts`.

**Comment by es128** [comment]
Yes, that makes sense. I had forgotten that we started working on `liveJS` here.

**Comment by rstacruz** [comment]
Done!

**Pull request merged**
