### PR TITLE
Don't reload if autoreload='false' attr is set on stylesheet link

### PR DESCRIPTION
**Pull request by shreeve**
This allows you to prevent certain stylesheets from reloading when a local stylesheet is changed.

Use like this:

```javascript
  <link href='//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet' type='text/css' autoreload='false'>
  <link href='/stylesheets/vendor.css' rel='stylesheet' type='text/css'>
  <link href='/stylesheets/app.css' rel='stylesheet' type='text/css'>
```

### CODE REVIEW

**Comment by paulmillr** [comment]
Awsm! maybe use `data-autoreload`, it'll be valid HTML then

**Comment by shreeve** [comment]
Cool... just added, works great!

**Comment by es128** [comment]
Could you also document this capability in the readme before we merge this PR?

**Comment by shreeve** [comment]
Thanks @es128!

**Pull request merged**
